#Build w/Maven 3.5-JDK-8
FROM maven:3.5-jdk-8-alpine as builder
COPY src /usr/src/app/src
COPY pom-vuln.xml /usr/src/app/pom.xml
RUN mvn -f /usr/src/app/pom.xml clean package

# Use an official OpenJDK runtime as a parent image
FROM openjdk:8-jre-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the fat jar into the container at /app
COPY --from=builder /usr/src/app/target/text4shell-poc.jar /app

# Document Port 8080 Listening of application
EXPOSE 8080

# Run jar file when the container launches
CMD ["java", "-jar", "text4shell-poc.jar"]
