# Use a recent official Amazon Corretto runtime image as a parent image
FROM amazoncorretto:20-alpine

# Update Corretto packages
RUN apk update && apk upgrade

# Set the working directory to /app
WORKDIR /app

# Copy the fat jar into the container at /app
COPY target/text4shell-poc.jar /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run jar file when the container launches
CMD ["java", "-jar", "text4shell-poc.jar"]
